// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmamribntqiszihqvxvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtYW1yaWJudHFpc3ppaHF2eHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTM0OTIsImV4cCI6MjA2OTcyOTQ5Mn0.wg5xhyJRr_dyeL8-bRJnTs1JSP0L6yLH0_ZR-06LfzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});